# Generated by Django 5.1.5 on 2025-04-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('gemini', 'Géminis'), ('chatgpt', 'Chat-GPT'), ('llama', 'Llama')], default='gemini', max_length=10)),
                ('is_local', models.BooleanField(default=False)),
            ],
        ),
    ]
