# Generated by Django 5.1.5 on 2025-04-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asistente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelsIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='local', max_length=90, null=True)),
                ('api_keys', models.TextField(blank=True, default='', null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='configuration',
            name='model',
            field=models.CharField(choices=[('gemini', 'Géminis'), ('chatgpt', 'Chat-GPT'), ('llama', 'Llama'), ('gemma', 'Gemma')], default='gemini', max_length=10),
        ),
    ]
