# Generated by Django 5.0 on 2024-12-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='img_back',
            field=models.ImageField(blank=True, null=True, upload_to='media/planes'),
        ),
    ]
