# Generated by Django 5.0 on 2024-12-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0002_plan_img_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
