# Generated by Django 5.0 on 2024-12-18 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0006_rename_proces_end_sale_credit_fiscal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='Estudios.plan')),
            ],
            options={
                'verbose_name': 'caracteristica',
                'verbose_name_plural': 'caracteristicas',
            },
        ),
    ]
