# Generated by Django 5.0 on 2024-12-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0010_sale_email_client_sale_is_cliente_sale_name_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
