# Generated by Django 5.0 on 2024-12-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0011_alter_sale_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
