# Generated by Django 5.0 on 2024-12-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0012_alter_sale_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/ventas'),
        ),
    ]
