# Generated by Django 5.0 on 2024-12-20 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0013_sale_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='mount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.BooleanField(default=True)),
                ('date_opening', models.DateTimeField(auto_now_add=True)),
                ('date_close', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='box', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto'), ('cierre', 'Cierre'), ('apertura', 'Apertura'), ('editar', 'Editar'), ('crear', 'Crear'), ('eliminar', 'Eliminar'), ('venta', 'Venta'), ('reserva', 'Reserva'), ('pago', 'Pago'), ('finalizar', 'Finalizar')], max_length=15)),
                ('mount', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='Sin descripción', null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='Estudios.box')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_move', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
