# Generated by Django 5.0 on 2024-12-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0017_alter_sale_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='time',
            field=models.CharField(blank=True, choices=[('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00')], default='', max_length=5, null=True, verbose_name='Hora seleccionada'),
        ),
    ]
