# Generated by Django 5.0 on 2024-12-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0018_alter_sale_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='role',
            field=models.CharField(choices=[('estandard', 'Estandar'), ('administrativo', 'Administrativo'), ('administrador', 'Administrador')], default='estandard', max_length=20),
        ),
    ]
