# Generated by Django 5.0 on 2024-12-29 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0023_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudios',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados_estudio', to='Estudios.empleado'),
        ),
    ]
