# Generated by Django 5.0 on 2024-12-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0026_sale_cosumidor_final_sale_credito_fiscal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='cosumidor_final',
            field=models.CharField(blank=True, default='B02000000', max_length=255, null=True, verbose_name='Detalles Consumidor Final'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='credito_fiscal',
            field=models.CharField(blank=True, default='B01000000', max_length=255, null=True, verbose_name='Detalles Fiscales'),
        ),
    ]
