# Generated by Django 5.0 on 2025-01-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0027_alter_sale_cosumidor_final_alter_sale_credito_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cosumidor_final',
            field=models.CharField(blank=True, default='B02000000', max_length=255, null=True, verbose_name='Consumidor Final'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='credito_fiscal',
            field=models.CharField(blank=True, default='B01000000', max_length=255, null=True, verbose_name='Creditos Fiscales'),
        ),
    ]
