# Generated by Django 5.0 on 2025-01-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0029_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='img',
            field=models.ImageField(null=True, upload_to='media/momentos'),
        ),
    ]
