# Generated by Django 5.0 on 2025-01-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0030_alter_moment_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='img',
            field=models.ImageField(null=True, upload_to='media/servicios'),
        ),
    ]
