# Generated by Django 5.0 on 2025-01-08 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0031_alter_service_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mount', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='Sin descripción', null=True)),
                ('payment', models.BooleanField(default=False)),
                ('last_payment_date', models.DateField(blank=True, null=True, verbose_name='Fecha del último pago')),
                ('next_payment_date', models.DateField(blank=True, null=True, verbose_name='Fecha del próximo pago')),
                ('estudio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='Estudios.estudios')),
            ],
        ),
    ]
