# Generated by Django 5.0 on 2025-01-08 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0032_facturacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='estudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_estudios', to='Estudios.estudios'),
        ),
    ]
