# Generated by Django 5.0 on 2025-01-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0033_profile_estudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacion',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/factura'),
        ),
    ]
