# Generated by Django 5.0 on 2025-01-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0035_estudios_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='pk_plan',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
