# Generated by Django 5.1.5 on 2025-02-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0036_sale_pk_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.BooleanField(default=True),
        ),
    ]
