# Generated by Django 5.1.5 on 2025-02-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0037_alter_sale_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='name_company_client',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='rnc_client',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
