# Generated by Django 5.1.5 on 2025-02-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0038_sale_name_company_client_sale_rnc_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la creación'),
        ),
    ]
