# Generated by Django 5.1.5 on 2025-02-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0040_alter_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudios',
            name='background_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/estudios', verbose_name='Imagen de fondo'),
        ),
    ]
