# Generated by Django 5.1.5 on 2025-02-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0041_estudios_background_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='phone_no_formate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
