# Generated by Django 5.1.5 on 2025-02-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0042_sale_phone_no_formate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=25)),
                ('phone', models.CharField(blank=True, default='', max_length=15)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/contact')),
            ],
        ),
    ]
