# Generated by Django 5.1.5 on 2025-02-10 09:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0044_sale_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de creacion'),
        ),
    ]
