# Generated by Django 5.1.5 on 2025-02-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0046_alter_contact_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='descrition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
