# Generated by Django 5.1.5 on 2025-02-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0047_sale_descrition'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='saled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de facturación'),
        ),
    ]
