# Generated by Django 5.1.5 on 2025-03-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0048_sale_saled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_oferta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='monto_oferta',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='porcentaje_oferta',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_oferta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='monto_oferta',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='porcentaje_oferta',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
