# Generated by Django 5.1.5 on 2025-03-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0049_plan_is_oferta_plan_monto_oferta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='monto_oferta',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='is_oferta',
            new_name='is_offer',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='porcentaje_oferta',
            new_name='mount',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='monto_oferta',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='is_oferta',
            new_name='is_offer',
        ),
        migrations.RemoveField(
            model_name='service',
            name='porcentaje_oferta',
        ),
        migrations.AddField(
            model_name='plan',
            name='porcent_discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='mount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='porcent_discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
