# Generated by Django 5.2 on 2025-05-06 06:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0050_rename_monto_oferta_plan_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='created_box',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
