# Generated by Django 5.2 on 2025-05-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0051_box_created_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='created_box',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
