# Generated by Django 5.1.5 on 2025-06-10 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0052_alter_box_created_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('credito', 'Crédito Fiscal'), ('consumidor', 'Consumidor Final')], default='consumidor', max_length=13, verbose_name='Tipo de Venta'),
        ),
    ]
