# Generated by Django 5.1.5 on 2025-06-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0053_alter_sale_date_alter_sale_sale_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adicional',
            name='pay',
            field=models.BooleanField(default=False),
        ),
    ]
