# Generated by Django 5.1.5 on 2025-07-22 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0055_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='Estudios.sale'),
        ),
    ]
